# docker-compose.yml
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - mern_stack_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_stack_network:
    external: true

volumes:
  mongo-data:
