version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turbo_app
    ports:
      - '3000:3000'
      - '3001:3001'
      - '8000:8000'
    networks:
      - mern_stack_network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/task_tracker
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "yarn", "dev" ]

networks:
  mern_stack_network:
    external: true
